### ISSUE TITLE
Bokeh no longer depends on bkcharts

### ISSUE THREAD

**Issue by bryevdv** [conda-forge/bokeh-feedstock#12]
We removed the dependency early, with `0.12.9` I believe this has been said it should simplify some things for C-F

**Comment by bryevdv** [comment]
cc @ocefpaf @jakirkham

**Comment by jakirkham** [comment]
Thanks for the heads up. Guess we missed a few packages over the last month. Any value in packaging the ones inbetween or should we just fast forward to 0.12.9?

**Comment by bryevdv** [comment]
Probably not, `0.12.8` was a botched release, it does't really exist

**Comment by bryevdv** [comment]
For reference this is the full list of runtime deps now:
```
# state our runtime deps here, also used by meta.yaml (so KEEP the spaces)
REQUIRES = [
    'six >=1.5.2',
    'PyYAML >=3.10',
    'python-dateutil >=2.1',
    'Jinja2 >=2.7',
    'numpy >=1.7.1',
    'tornado >=4.3',
]

# handle the compat difference for futures (meta.yaml handles differently)
if sys.version_info[:2] == (2, 7):
    REQUIRES.append('futures >=3.0.3')
```

also note that `bokeh.charts` and `bokeh.core.compat` are both entirely gone

**Comment by jakirkham** [comment]
Please let me know if PR ( https://github.com/conda-forge/bokeh-feedstock/pull/13 ) looks ok.

**Comment by bryevdv** [comment]
@jakirkham pretty much, I'm not familiar with the details of C-F recipes so some of its unfamiliar to me, but the one parts look OK. My only comment is that the list of test imports is not completely comprehensive, there has been some refactoring to split some things up. I am not sure if comprehensive is the goal, though.

**Comment by jakirkham** [comment]
Thanks for taking a look.

> My only comment is that the list of test imports is not completely comprehensive, there has been some refactoring to split some things up. I am not sure if comprehensive is the goal, though.

Yeah things have changed over time and we haven't done a great job of reflecting this in the imports. It's not a requirement to import everything. Just tends to be the case when generating a recipe with `conda-build` that it covers a lot of imports. We can certainly add to the imports included if there are things that you are wanting to see in particular. I might save it for a follow-up PR though.
