### ISSUE TITLE
Remove/split-out *.js.map files

### ISSUE THREAD

**Issue by jcrist** [conda-forge/bokeh-feedstock#36]
The `*.js.map` files are non-negligible in size:

```
$ find ./lib/python3.7/site-packages/bokeh -type f -name '*.js.map' -exec du -ch {} +
244K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-widgets.js.map
940K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-tables.min.js.map
124K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-api.js.map
760K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-tables.js.map
320K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-widgets.min.js.map
184K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-api.min.js.map
1.9M    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh.js.map
156K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-gl.min.js.map
2.7M    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh.min.js.map
 12M    ./lib/python3.7/site-packages/bokeh/server/static/js/compiler.js.map
124K    ./lib/python3.7/site-packages/bokeh/server/static/js/bokeh-gl.js.map
 19M    total
```

When installing in a docker image it may be useful to remove them to reduce image size.

Right now I'm removing them after installation, which is fine if not ideal.

**Comment by ocefpaf** [comment]
I'm always :+1: on making the packages smaller but I don't know the first thing about those files. It is OK to just remove them?

**Comment by jcrist** [comment]
AFAICT these are mostly useful for debugging js tracebacks, and not needed in production? I'm not a web-dev either though. Perhaps @canavandl or @bryevdv has thoughts?

**Comment by bryevdv** [comment]
Those are only useful for development (of BokehJS itself). We don't publish them to CDN at all, for instance. I don't see why removing them would be a problem.

**Comment by jcrist** [comment]
Thanks for responding Bryan. Can you think of any other file extensions we may want to strip in the build?

**Comment by bryevdv** [comment]
I should add, these files are also useful for debugging releases when `BOKEH_MINIFIED=no` so I do think they should be part of the package generally (I was trying to debate if maybe we should just not include them at all on our side).

I can't think of too many files offhand, but I have not looked at the package contents lately. If you know you will only be using minified resources, you could probably strip out the unminified versions. If you don't make use of any customjs or custom extensions then the entire `static/lib` dir could possibly go. This is actually a good question for @mattpap

**Comment by jcrist** [comment]
In our case at least we're only using the minified versions - removing the unminified versions is also a big enough savings that it's worth doing. I don't know if it would make sense to remove the unminified versions from the package on conda-forge though, since afaict users do have access to them from the `bokeh.resources` package.

**Comment by ocefpaf** [comment]
> In our case at least we're only using the minified versions - removing the unminified versions is also a big enough savings that it's worth doing. I don't know if it would make sense to remove the unminified versions from the package on conda-forge though, since afaict users do have access to them from the `bokeh.resources` package.

In that case removing then is not an option. We would need a split-package to do that.

**Comment by bryevdv** [comment]
I'm not sure which package on C-F you mean, they definitely can't be removed from the Bokeh package. I thought this discussion was about configuring a Docker image, which seems more reasonable, depending if you can count on assumptions about how the docker image will be used.

**Comment by jcrist** [comment]
I guess it's about two things:

- What can be removed from the bokeh conda-forge package (I think just the `*.js.map` files)?
- What can be removed manually in a docker image?

**Comment by jcrist** [comment]
I believe with #35 this can be closed.
