### ISSUE TITLE
3.8 release for Windows

### ISSUE THREAD

**Issue by letmaik** [conda-forge/bokeh-feedstock#43]
`win-64/bokeh-1.4.0-py38_0.tar.bz2` is marked as [broken](https://anaconda.org/conda-forge/bokeh/files). I'm wondering when a fixed version will be pushed as this prevents installing other packages that depend on it, like scikit-image.

**Comment by ocefpaf** [comment]
2.0.0 and 2.0.1 are available for py38 and Windows. Closing this.
