### ISSUE TITLE
Defend against Tornado 4.5

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/bokeh-feedstock#8]
Bokeh 0.12.6 and Tornado 4.5 have a known incompatibility.  I *think* that the solution within defaults was to restrict requirements so that installing bokeh would downgrade tornado to 4.5.  It looks like this solution hasn't been applied to the conda-forge feedstock

```
mrocklin@carbon:~$ conda create -n test-bokeh bokeh tornado --dry-run -c conda-forge
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/mrocklin/Software/anaconda/envs/test-bokeh:

The following NEW packages will be INSTALLED:

    bokeh:            0.12.5-py36_0      conda-forge  # <<------
    ca-certificates:  2017.1.23-1        conda-forge
    certifi:          2017.4.17-py36_0   conda-forge
    cycler:           0.10.0-py36_0      conda-forge
    dbus:             1.10.10-3          conda-forge
    expat:            2.1.0-2            conda-forge
    fontconfig:       2.12.1-4           conda-forge
    freetype:         2.7-1              conda-forge
    gettext:          0.19.7-1           conda-forge
    glib:             2.51.4-0           conda-forge
    gst-plugins-base: 1.8.0-0            conda-forge
    gstreamer:        1.8.0-1            conda-forge
    icu:              58.1-1             conda-forge
    jinja2:           2.9.5-py36_0       conda-forge
    jpeg:             9b-0               conda-forge
    libffi:           3.2.1-3            conda-forge
    libiconv:         1.14-4             conda-forge
    libpng:           1.6.28-0           conda-forge
    libxcb:           1.12-1             conda-forge
    libxml2:          2.9.4-4            conda-forge
    markupsafe:       0.23-py36_1        conda-forge
    matplotlib:       2.0.0-np112py36_3  conda-forge
    mkl:              2017.0.1-0                    
    ncurses:          5.9-10             conda-forge
    numpy:            1.12.1-py36_0                 
    openssl:          1.0.2k-0           conda-forge
    pandas:           0.19.2-np112py36_1 conda-forge
    pcre:             8.39-0             conda-forge
    pip:              9.0.1-py36_0       conda-forge
    pyparsing:        2.2.0-py36_0       conda-forge
    pyqt:             5.6.0-py36_2       conda-forge
    python:           3.6.1-0            conda-forge
    python-dateutil:  2.6.0-py36_0       conda-forge
    pytz:             2017.2-py36_0      conda-forge
    pyyaml:           3.12-py36_1        conda-forge
    qt:               5.6.2-2            conda-forge
    readline:         6.2-0              conda-forge
    requests:         2.13.0-py36_0      conda-forge
    setuptools:       33.1.1-py36_0      conda-forge
    sip:              4.18-py36_1        conda-forge
    six:              1.10.0-py36_1      conda-forge
    sqlite:           3.13.0-1           conda-forge
    tk:               8.5.19-1           conda-forge
    tornado:          4.5.1-py36_0       conda-forge  # <<------
    wheel:            0.29.0-py36_0      conda-forge
    xorg-libxau:      1.0.8-3            conda-forge
    xorg-libxdmcp:    1.1.2-3            conda-forge
    xz:               5.2.2-0            conda-forge
    yaml:             0.1.6-0            conda-forge
    zlib:             1.2.11-0           conda-forge
```

More generally, this exposes a rift in maintenance.  Bokeh developers tend to maintain the recipes in the defaults channel but now some people (like the dask development toolchain) rely on the conda-forge channel for most packages.  Is it on the bokeh devs to take on this new maintenance burden?  Should there be more open lines of communication to the conda-forge recipe maintainers?

cc @jakirkham @bryevdv

**Comment by ocefpaf** [comment]
>  this exposes a rift in maintenance.

Or maybe a problem with our tools :grimacing: 

I face issues like that a lot when naively updating a `feedstock` to the latest package version without checking if the requirements have changed. We need a way to re-generate the recipe, or parts of the recipe, using the metadata that is available to us. (Of course having the devs as maintainers do help but should not be needed.)

**Comment by jakirkham** [comment]
So we haven't released `bokeh` 0.12.6 yet. We can certainly address this when we upgrade.

As far as keeping lines of communication open, @almarklein had volunteered to help maintain the recipe here. That should help with these sorts of issues.

**Comment by bryevdv** [comment]
> I face issues like that a lot when naively updating a feedstock to the latest package version without checking if the requirements have changed.

Agreed but just FYI that's not what happened in this case. Tornado 4.5 came out *after* the Bokeh `0.12.6` release.

**Comment by ocefpaf** [comment]
> Tornado 4.5 came out *after* the Bokeh `0.12.6` release. 

Good to know .(So in a way bokeh source dist needs a patch release too :smile: )

**Comment by jakirkham** [comment]
Does this PR ( https://github.com/bokeh/bokeh/pull/6155 ) fix the issue completely? If so, we could patch it and release.

**Comment by bryevdv** [comment]
@jakirkham yes that PR fixed the issue, which is no longer present in master or recent dev builds. Either patching, or or updating the dependencies to exclude Tornado 4.5 (what `defaults` did) seem fine to me.

**Comment by jakirkham** [comment]
> ... or updating the dependencies to exclude Tornado 4.5 (what `defaults` did)...

`defaults` has access to some features that we don't. For instance they can hotfix pinnings without rebuilding a package. The best we can do on that front is rebuild the package to exclude that version of Tornado. This ends up being a mixed bag as the solver may try to get an older version of the `bokeh` package (typically the same version, but an older build number) so that it can upgrade `tornado` to the latest version. We can try pulling old packages to address this, but it is a bit messy. Solving this problem in `conda` is tricky. I think adding a feature like that described in issue ( https://github.com/conda/conda/issues/3968 ) will help, but there is probably more to the story.

<br>

To avoid this, my proposal would be to patch and release a new build of `bokeh`. If anyone has concerns with this, please let me know.

**Comment by bryevdv** [comment]
Seems reasonable. Unfortunately we are not quite in a place to release `0.12.6` off `master` and don't have process (or time to develop one atm) for releasing off a branch. FWIW `0.12.6` should be ready around the end of May.

**Comment by mrocklin** [comment]
So we're stuck in this state for a month or so?  FWIW I hear about this pretty frequently.

Can I recommend that we just pull the bokeh 0.12.5 package from conda-forge?

**Comment by mrocklin** [comment]
To be explicit, there is a github issue or comment on the gitter chat from a new user every couple of days about this.  That is probably tip-of-the-iceberg for dask users, which is probably tip-of-the-iceberg for bokeh users generally.

**Comment by ocefpaf** [comment]
> So we're stuck in this state for a month or so? FWIW I hear about this pretty frequently.

My understanding is that a simple PR pinning `tornado` and bumping the build number is enough. Not sure why would that be difficult here. I'll do it...

**Comment by mrocklin** [comment]
@jakirkham says:

> defaults has access to some features that we don't. For instance they can hotfix pinnings without rebuilding a package. The best we can do on that front is rebuild the package to exclude that version of Tornado. This ends up being a mixed bag as the solver may try to get an older version of the bokeh package (typically the same version, but an older build number) so that it can upgrade tornado to the latest version.

**Comment by ocefpaf** [comment]
PR #9 should fix this @mrocklin.

**Comment by jakirkham** [comment]
> So we're stuck in this state for a month or so? FWIW I hear about this pretty frequently.

Was waiting to hear from @bryevdv that my proposed fix was ok. As that is the case, I'm happy to go ahead with it. However, it seems the other problematic option is being pursued too. I can still put my proposal together if you would like, but it would be nice if we are all on the same page first.

**Comment by bryevdv** [comment]
If a new build with updated dependencies and build number is made, can the old build not also be completely removed?

**Comment by ocefpaf** [comment]
> If a new build with updated dependencies and build number is made, can the old build not also be completely removed?

I am planning on doing so :wink: (we already did that many times BTW in the past. It is not "problematic.")

**Comment by jakirkham** [comment]
There's still the possibility the solver may try to upgrade to the latest `tornado` and downgrade `bokeh`.

**Comment by mrocklin** [comment]
That would be fine with me

**Comment by ocefpaf** [comment]
> There's still the possibility the solver may try to upgrade to the latest `tornado` and downgrade `bokeh`.

Yeah. And that breaks all of the pinning on conda-forge. Do you really want people to have a broken package instead of the current status quo that we all use?

**Comment by jakirkham** [comment]
No, as I said before I'd rather patch it with the fix from upstream.

**Comment by ocefpaf** [comment]
You can definitely do that. But I don't want to leave people waiting.

**Comment by jakirkham** [comment]
> That would be fine with me

Does Bokeh 0.12.4 not have this problem with newer Tornado versions? If not, sure either fix is fine.

**Comment by bryevdv** [comment]
I expect all previous versions are incompatible with tornado 4.5 but haven't rigorously verified this.

**Comment by jakirkham** [comment]
Ok, just put together the alternative proposal in PR ( https://github.com/conda-forge/bokeh-feedstock/pull/10 ). Please let us know your preferences.

**Comment by mrocklin** [comment]
Given @bryevev's comment 

> I expect all previous versions are incompatible with tornado 4.5 but haven't rigorously verified this.

I suspect that this is still a live issue, particularly because conda does seem to prefer downgrading bokeh over tornado (at least for my use case)

```
mrocklin@carbon:~$ conda create -n foo --dry-run -c conda-forge dask distributed 
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/mrocklin/Software/anaconda/envs/foo:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.6.1               |                1        18.9 MB  conda-forge
    tornado-4.5.1              |           py36_0         620 KB  conda-forge
    partd-0.3.8                |           py36_0          29 KB  conda-forge
    wheel-0.29.0               |           py36_0          82 KB  conda-forge
    matplotlib-2.0.1           |      np112py36_0         9.4 MB  conda-forge
    bokeh-0.12.4               |           py36_0         4.6 MB  conda-forge
    dask-0.14.2                |           py36_0         837 KB  conda-forge
    distributed-1.16.2         |           py36_0         554 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        35.0 MB

The following NEW packages will be INSTALLED:

    bokeh:            0.12.4-py36_0      conda-forge
    boto3:            1.4.4-py36_0       conda-forge
    botocore:         1.5.39-py36_0      conda-forge
    ca-certificates:  2017.1.23-1        conda-forge
    certifi:          2017.4.17-py36_0   conda-forge
    click:            6.7-py36_0         conda-forge
    cloudpickle:      0.2.2-py36_2       conda-forge
    cycler:           0.10.0-py36_0      conda-forge
    dask:             0.14.2-py36_0      conda-forge
    dbus:             1.10.10-3          conda-forge
    distributed:      1.16.2-py36_0      conda-forge
    docutils:         0.13.1-py36_0      conda-forge
    expat:            2.1.0-2            conda-forge
    fontconfig:       2.12.1-4           conda-forge
    freetype:         2.7-1              conda-forge
    gettext:          0.19.7-1           conda-forge
    glib:             2.51.4-0           conda-forge
    gst-plugins-base: 1.8.0-0            conda-forge
    gstreamer:        1.8.0-1            conda-forge
    heapdict:         1.0.0-py36_0       conda-forge
    icu:              58.1-1             conda-forge
    jinja2:           2.9.5-py36_0       conda-forge
    jmespath:         0.9.2-py36_0       conda-forge
    jpeg:             9b-0               conda-forge
    libffi:           3.2.1-3            conda-forge
    libiconv:         1.14-4             conda-forge
    libpng:           1.6.28-0           conda-forge
    libxcb:           1.12-1             conda-forge
    libxml2:          2.9.4-4            conda-forge
    locket:           0.2.0-py36_1       conda-forge
    markupsafe:       0.23-py36_1        conda-forge
    matplotlib:       2.0.1-np112py36_0  conda-forge
    mkl:              2017.0.1-0                    
    msgpack-python:   0.4.8-py36_0       conda-forge
    ncurses:          5.9-10             conda-forge
    numpy:            1.12.1-py36_0                 
    openssl:          1.0.2k-0           conda-forge
    pandas:           0.19.2-np112py36_1 conda-forge
    partd:            0.3.8-py36_0       conda-forge
    pcre:             8.39-0             conda-forge
    pip:              9.0.1-py36_0       conda-forge
    psutil:           5.2.1-py36_0       conda-forge
    pyparsing:        2.2.0-py36_0       conda-forge
    pyqt:             5.6.0-py36_2       conda-forge
    python:           3.6.1-1            conda-forge
    python-dateutil:  2.6.0-py36_0       conda-forge
    pytz:             2017.2-py36_0      conda-forge
    pyyaml:           3.12-py36_1        conda-forge
    qt:               5.6.2-2            conda-forge
    readline:         6.2-0              conda-forge
    requests:         2.13.0-py36_0      conda-forge
    s3fs:             0.0.9-py36_0       conda-forge
    s3transfer:       0.1.10-py36_1      conda-forge
    setuptools:       33.1.1-py36_0      conda-forge
    sip:              4.18-py36_1        conda-forge
    six:              1.10.0-py36_1      conda-forge
    sortedcontainers: 1.5.3-py36_0       conda-forge
    sqlite:           3.13.0-1           conda-forge
    tblib:            1.3.2-py36_0       conda-forge
    tk:               8.5.19-1           conda-forge
    toolz:            0.8.2-py36_0       conda-forge
    tornado:          4.5.1-py36_0       conda-forge
    wheel:            0.29.0-py36_0      conda-forge
    xorg-libxau:      1.0.8-3            conda-forge
    xorg-libxdmcp:    1.1.2-3            conda-forge
    xz:               5.2.2-0            conda-forge
    yaml:             0.1.6-0            conda-forge
    zict:             0.1.2-py36_0       conda-forge
    zlib:             1.2.11-0           conda-forge
```

**Comment by ocefpaf** [comment]
@mrocklin it looks like many versions of bokeh, from 0.11.1 to 0.12.5, where added to conda-forge. The only proper solution is to propagate down the tornado fix or abandon the support for the old versions.

**Comment by jakirkham** [comment]
The patch is included in PR ( https://github.com/conda-forge/bokeh-feedstock/pull/10 ) with another build number bump. Have rebased on top of these changes and removed the pin. Please take a look.

**Comment by ocefpaf** [comment]
@mrocklin the Linux packages are in and everything is working foe me:

```shell
> conda install -c conda-forge bokeh
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/filipe/miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2017.0.1               |                0       128.2 MB  defaults
    numpy-1.12.1               |           py36_0         7.0 MB  defaults
    tornado-4.4.3              |           py36_0         590 KB  conda-forge
    bokeh-0.12.5               |           py36_1         4.2 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       140.0 MB

The following NEW packages will be INSTALLED:

    bokeh:            0.12.5-py36_1      conda-forge
    cycler:           0.10.0-py36_0      conda-forge
    dbus:             1.10.10-3          conda-forge
    expat:            2.1.0-2            conda-forge
    fontconfig:       2.12.1-4           conda-forge
    freetype:         2.7-1              conda-forge
    gettext:          0.19.7-1           conda-forge
    glib:             2.51.4-0           conda-forge
    gst-plugins-base: 1.8.0-0            conda-forge
    gstreamer:        1.8.0-1            conda-forge
    icu:              58.1-1             conda-forge
    jinja2:           2.9.5-py36_0       conda-forge
    jpeg:             9b-0               conda-forge
    libiconv:         1.14-4             conda-forge
    libpng:           1.6.28-0           conda-forge
    libxcb:           1.12-1             conda-forge
    libxml2:          2.9.4-4            conda-forge
    markupsafe:       0.23-py36_1        conda-forge
    matplotlib:       2.0.1-np112py36_0  conda-forge
    mkl:              2017.0.1-0         defaults   
    numpy:            1.12.1-py36_0      defaults   
    pandas:           0.19.2-np112py36_1 conda-forge
    pcre:             8.39-0             conda-forge
    pyparsing:        2.2.0-py36_0       conda-forge
    pyqt:             5.6.0-py36_2       conda-forge
    qt:               5.6.2-2            conda-forge
    sip:              4.18-py36_1        conda-forge
    tornado:          4.4.3-py36_0       conda-forge
    xorg-libxau:      1.0.8-3            conda-forge
    xorg-libxdmcp:    1.1.2-3            conda-forge
```

It may take a while for the OS X and Windows packages though.

PS: all the broken versions are now labeled `broken` and, if anyone wants to maintain them, they should backport a solution and send a PR to fix it. Only the latest version `0.12.5` build `1` is fixed in `conda-forge`. (And I won't fix the old ones since one can easily get them from `defaults`. IMO `conda-forge` is to augment `defaults` and not replicate it.)
