### ISSUE TITLE
Heads up for 3.0 changes

### ISSUE THREAD

**Issue by bryevdv** [conda-forge/bokeh-feedstock#82]
### Comment:

cc @ocefpaf @jakirkham @philippjfr 

I wanted to draw everyone's attention to a currently in-flight PR: https://github.com/bokeh/bokeh/pull/12306

This PR consolidates configuration and setuptools build in `pyproject.toml`, and replaces `versioneer` with [`setuptools-git-versioning`](https://setuptools-git-versioning.readthedocs.io/en/stable/index.html) in the process. A half a dozen or more various files are able to be deleted. The PR is still WIP but I am committed to pushing it through, and there are not any outstanding blockers that I can see. 

However, I did have to switch up the conda recipe to build the conda package by installing a wheel as described here:

https://docs.conda.io/projects/conda-build/en/latest/user-guide/wheel-files.html#building-a-conda-package-from-a-wheel-file

I had tried to emulate the conda-forge recipe, and build the conda package by calling `pip install .` form an sdist. This *should* work, and in fact does work just fine when doing so manually. However,  ***it fails when done by conda-build [1]***. Since it works by hand, and not inside conda-build, I have to assume the issue lies with conda-build somehow. But I've expended as much personal time and effort as I am going to on this problem, so unless someone else figures out an explanation or fix, I expect the conda-forge recipe will also need to build directly from a wheel (downloaded from pypi).

*[1] Specifically, it generates a package that reports "0.0.0" as the version, which is especially weird/annoying as the correct version can otherwise be seen in many places of the conda-build log.*

**Comment by jakirkham** [comment]
Have not used `setuptools-git-version`, but recall `setuptools-scm` had similar issues with versioning being lost in some cases. Think this is something `setuptools-scm` ultimately addressed [via additional settings for git archives]( https://github.com/pypa/setuptools_scm#git-archives ). It's possible a similar configuration is needed by `setuptools-git-version` (assuming it has the needed functionality).

**Comment by bryevdv** [comment]
I did look at `setuptools-scm` but it' auto-magic "try to invent the next version" behavior is not something I can make work for us. I expect it is something similar, but I am curious, where does conda built use git archives? My understanding is that these are the cases (that variously have issues for us):

* `path` -- does a bare copy of the local source, scm-based versioning doesn't work on non-repo copy
* `git_url` -- does a clone of the local repo, does not work for us since BokehJS is no longer installed in the new tree
* `url` -- works for wheel, not for sdist

Or do you mean the contents of the sdist are a "git archive"? If so I can try to raise an issue on the `setuptools-git-version` tracker.

**Comment by bryevdv** [comment]
That said I am also still curious why a manual `pip install .` in the sdist works but telling conda-build to do that does not work. But I think conda-build sets a bunch of obscure pip environment vars so maybe that is it.

**Comment by jakirkham** [comment]
Right not trying suggest a particular `setuptools` VCS aware package is preferable. Just recalling past issues that these kinds of tools can run into.

Sure it would only come up when using a particular form of source. Not sure what source type was used here. So this particular wrinkle may or may not be relevant.

These are [the relevant `pip` environment variables Conda sets]( https://github.com/conda/conda-build/blob/5102287ae379955fecf45e60c0fd3d1318b9ba85/conda_build/build.py#L2597-L2617 ). One could try setting these environment variables before running `pip` and see how they behave.

**Comment by bryevdv** [comment]
I don't really have much bandwidth to experiment. Offhand, maybe this?
```
env["PIP_NO_BUILD_ISOLATION"] = 'False'
```
I think the pyproject build deps are only installed in the isolated case? If so then perhaps the SCM version tool is not installed, and then perhaps there is this silent 0.0.0 failure rather than a crash. Assuming all that is true, then possibly explicitly installing the SCM version tool in the build env would help. I can try that, at least.

**Comment by jakirkham** [comment]
Was `setuptools-git-version` added to the `host` dependencies of the recipe?

**Comment by bryevdv** [comment]
No, I only added it to `pyproject.toml`
```

 [build-system]
 requires = ["setuptools>=64", "setuptools-git-versioning", "colorama"]
 build-backend = "setuptools.build_meta"
```

**Comment by jakirkham** [comment]
Typically Python build dependencies are added in `requirements/host`. Perhaps adding these requirements to `host` addresses the issue?

**Comment by bryevdv** [comment]
That was my one intention to try above :) 

> possibly explicitly installing the SCM version tool in the build env would help. I can try that, at least.

**Comment by bryevdv** [comment]
Unfortunately adding the `build-requires` dependencies to the `host` section of the recipe did not solve the issue. At least on our end, we will definitely stick with installing from a wheel, which seems to work just fine and is explicitly described in the conda docs.

**Comment by bryevdv** [comment]
I think conda-forge may end up having to use the wheel as well. Currently the sdists produced in CI are broken, but the wheels are not. I am about to throw my hands up and only publish wheels.

**Comment by jakirkham** [comment]
Are those file in a `MANIFEST.in` or equivalent?

**Comment by bryevdv** [comment]
I did manage to get working sdists: https://discuss.python.org/t/custom-build-steps-moving-bokeh-off-setup-py/16128/24?u=bryevdv

**Comment by jakirkham** [comment]
Interesting thanks for sharing 🙏

Yeah that makes sense. Am more interested in making sure everything that is needed is in the `sdist`.

**Comment by bryevdv** [comment]
> Yeah that makes sense. Am more interested in making sure everything that is needed is in the sdist.

👍  If you can figure out why the version is not correctly propagated to the dist-info in the conda-build case, I'm happy to put in any simple changes that would fix

**Comment by bryevdv** [comment]
@jakirkham just another minor FYI for the future, `contourpy >=1` is being added as a runtime dependency
